apiVersion: v1
kind: Service
metadata:
  name: helm-helloworld
spec:
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
    protocol: TCP
  selector:
    app: helm-helloworld
  type: NodePort  